Feat/#21 북마크 생성 기능 추가
gosopt-LionHeart/LionHeart-Server pull request #28
Opened 2023-07-12 09:40 UTC by sookyungg

## ✒️ 관련 이슈번호

- Closes #21

## 🔑 Key Changes

1. 내용
    - 북마크 생성 기능을 추가했습니다.

## 📢 To Reviewers
-

2023-07-12 18:06 UTC, orijoon98 requested changes
고생하셨슴니다 ~~!! 몇가지 자잘한 수정이 있슴니다!!

2023-07-12 18:06 UTC, orijoon98 commented on lionheart-domain/src/main/java/com/chiwawa/lionheart/domain/domain/articlebookmark/repository/ArticleBookmarkRepositoryImpl.java
> +			.fetchOne());
별건아닌데 where 절 내부에 엔터 한번씩 가능할까요... ㅎㅋㅎㅋ

2023-07-12 18:06 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articleBookmark/ArticleBookmarkServiceUtils.java
> +	public static void validateBookmark(Optional<ArticleBookmark> articleBookmark, boolean bookmarkStatus) {
네이밍이 조금 덜 직관적인것같아서 음.. validateBookmarkRequest 는 어떤가유..?!

2023-07-13 05:09 UTC, sookyungg commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articleBookmark/ArticleBookmarkServiceUtils.java
> +	public static void validateBookmark(Optional<ArticleBookmark> articleBookmark, boolean bookmarkStatus) {
조아요 ㅎㅎ!!

2023-07-13 06:37 UTC, orijoon98 approved these changes
고생하셨어용 :)))))))

2023-07-13 06:41 UTC, merged