Feat/#2 CI/CD 파이프라인 구축
gosopt-LionHeart/LionHeart-Server pull request #3
Opened 2023-07-05 14:08 UTC by PgmJun

## ✒️ 관련 이슈번호

- Closes #2 

## 🔑 Key Changes

1. 내용
    - nginx, S3, CodeDeploy, EC2를 사용한 CI/CD 무중단 배포 파이프라인 구축

## 📢 To Reviewers
- DEV1_APPLICATION / DEV2_APPLICATION / PROD_APPLICATION / AWS_SECRET 등등 git Secrets에 넣어둔 값들과
IAM, ec2 키페어 등등은 Notion 서버 라이온에 올려놓을게요!

2023-07-05 14:16 UTC, orijoon98 requested changes
오타가 있는 것 같아서 우선 RC 로 처리했습니다!
추가적으로 sh 파일이 안올라온 것 같은데 어디서 확인하면 될까욤?!
그리고 이런식으로 DEV1, DEV2 로 관리하는 방식을 처음봐서 참고할만한 레퍼런스 있다면 공유 부탁드립니당..!! 
Nginx 는 어떤 방식으로 활용하고 있는건가요!

2023-07-05 14:16 UTC, orijoon98 commented on .github/workflows/CD.yml
> +        echo "${{ secrets.PROD_APPLICATION }}" >> ./application-prod.yml
echo "${{ secrets.DEV1_APPLICATION }}" >> ./application-dev1.yml
echo "${{ secrets.DEV1_APPLICATION }}" >> ./application-dev2.yml

여기 확인 한번 부탁해요! 두번째도 DEV1 이 맞나요?!

2023-07-05 14:16 UTC, orijoon98 commented on .github/workflows/CD.yml
> +      run: cp ./scripts/*.sh ./deploy
sh 파일은 어디서 확인할 수 있나요!?

2023-07-05 15:36 UTC, PgmJun commented on .github/workflows/CD.yml
> +        echo "${{ secrets.PROD_APPLICATION }}" >> ./application-prod.yml
> echo "${{ secrets.DEV1_APPLICATION }}" >> ./application-dev1.yml echo "${{ secrets.DEV1_APPLICATION }}" >> ./application-dev2.yml
> 
> 여기 확인 한번 부탁해요! 두번째도 DEV1 이 맞나요?!

헉 오타입니다 감사합니다!!

2023-07-05 16:19 UTC, PgmJun commented
> 오타가 있는 것 같아서 우선 RC 로 처리했습니다! 추가적으로 sh 파일이 안올라온 것 같은데 어디서 확인하면 될까욤?! 그리고 이런식으로 DEV1, DEV2 로 관리하는 방식을 처음봐서 참고할만한 레퍼런스 있다면 공유 부탁드립니당..!! Nginx 는 어떤 방식으로 활용하고 있는건가요!

32기 솝트 서버 세미나 자료를 보며 만들었는데 노션 페이지가 잠금 상태라 공유가 불가능합니다ㅠㅠ

설명드리자면 참고한 레퍼런스에서는 프로퍼티 파일을 application.yml 하나만 두고 yml파일 내부에서 
set1, set2라는 서로 내용이 완전 동일하지만 포트만 다른 두 개의 환경을 통해 블루그린 방식으로 관리하는 것이 레퍼런스의 내용이었습니다!

이 부분은 제가 yml파일을 하나로 관리하지 않고 구분해서 관리해보고자 하는 과정에서 임의로 만들어본 코드인데 좋지 않은 코드인가요?! 그렇다면 수정하겠습니다!
사실 저도 처음 도전해보는 형태의 코드입니다!

구분해서 관리하고자 했던 이유는 현재 application.yml에선 공통적으로 필요한 환경변수를 관리하고
dev prod local 등의 yml 파일엔 각자 환경에 필요한 값들만 따로 관리하고 싶었기 때문입니다.
이때 레퍼런스처럼 set1 set2로 관리하기 위해서 dev를 1,2로 쪼개게 되었습니다..
어떻게 바꾸는게 좋을까요..!

nginx는 프로젝트 Root에 존재하는 scripts/**deploy.sh**와 ec2내에 세팅해둔 **switch.sh**를 통해서 dev1과 dev2의 로드밸런서 역할로 사용합니다!
nginx에서 dev1을 가리키고 있다가 default브랜치에 push가 들어오면 CD 마지막 과정에서 switch.sh를 통해 nginx가 dev2를 가리키게 스위칭합니다!

**switch.sh**
```
#!/bin/bash
echo "> 현재 구동중인 Port 확인"
CURRENT_PROFILE=$(curl -s http://localhost/profile)

# 쉬고 있는 set 찾기: set1이 사용중이면 set2가 쉬고 있고, 반대면 set1이 쉬고 있음
if [ $CURRENT_PROFILE == dev1 ]
then
  IDLE_PORT=8082
elif [ $CURRENT_PROFILE == dev2 ]
then
  IDLE_PORT=8081
else
  echo "> 일치하는 Profile이 없습니다. Profile: $CURRENT_PROFILE"
  echo "> 8081을 할당합니다."
  IDLE_PORT=8081
fi

echo "> 전환할 Port: $IDLE_PORT"
echo "> Port 전환"
echo "set \$service_url http://127.0.0.1:${IDLE_PORT};" |sudo tee /etc/nginx/conf.d/service-url.inc

PROXY_PORT=$(curl -s http://localhost/profile)
echo "> Nginx Current Proxy Port: $PROXY_PORT"

echo "> Nginx Reload"
sudo service nginx reload
~                             
```

2023-07-05 16:21 UTC, orijoon98 reviewed
질문사항 추가로 달아뒀어요!!

2023-07-05 16:21 UTC, orijoon98 commented on scripts/deploy.sh
> +/home/ubuntu/app/nonstop/switch.sh
switch.sh 은 어디서 확인할 수 있나욤?!

2023-07-05 16:21 UTC, orijoon98 commented on scripts/deploy.sh
> +fi
지금 스크립트를 살펴보면 profile 을 dev1, dev2 로 구별하는 이유가 현재 Nginx가 바라보고 있는 포트를 확인하기 위함인 것 같은데, yml 파일을 dev1, dev2 로 두개를 관리해서 다른 부분이 코드 뿐이라 오히려 관리 측면에서 불편할 것 같다는 생각이 들어용,,,!!

https://www.devjoon.com/56

![image](https://github.com/gosopt-LionHeart/LionHeart-Server/assets/74812188/ccd1ca90-eff5-48cc-8143-a3cab64d1809)

이거 제가 공유드렸던 블로그 링크인데, 여기서는 service_url 이라는 변수를 만들어두고 현재 바라보고 있는 url 을 지정해주는 방식이에요!

![image](https://github.com/gosopt-LionHeart/LionHeart-Server/assets/74812188/a50a5f88-3f6d-48f7-8012-9500ed830d1c)

그리고 이건 세가지 스크립트 중 마지막에 실행되는 스크립트인데, 보시면 현재 바라볼 Nginx url 변수를 업데이트 한 후에 Nginx 를 reload 하는 방식이라서 dev 설정 하나로도 블루/그린 방식으로 8081 포트 8082 포트 왔다갔다하면서 실행합니당!

yml 파일을 dev1, dev2 로 관리하기가 불편할 것 같다는 생각이 들어서 이런 방법도 있다.. 말해보는거구용!
혹시 지금처럼 dev 환경을 1, 2 로 관리했을 때의 장점이 다른게 더 있다면 이대로 가도 좋을 것 같아요!!

2023-07-05 16:28 UTC, orijoon98 commented on scripts/deploy.sh
> +/home/ubuntu/app/nonstop/switch.sh
위에 답변을 지금 봐서 ec2 에 있는 것 확인했어요!!
혹시 scripts 폴더에 같이 올리지 않고 ec2 에 직접 올려둔 이유가 있을까욤?!

2023-07-05 16:31 UTC, orijoon98 commented on scripts/deploy.sh
> +fi
이 부분도 위에 답변을 늦게봐서 정정해보자면

```
CURRENT_PORT=$(cat /etc/nginx/conf.d/service-url.inc | grep -Po '[0-9]+' | tail -1)
TARGET_PORT=0

if [ ${CURRENT_PORT} -eq 8081 ]; then
  TARGET_PORT=8082
elif [ ${CURRENT_PORT} -eq 8082 ]; then
  TARGET_PORT=8081
else
  echo "No WAS is connected to nginx"
  exit 1
fi
```

이 부분을 봐주시면 좋을 것 같은데 `CURRENT_PORT` 로 dev1, dev2 를 구별하는 역할이 가능할 것 같은데 dev 를 1, 2 로 나누는 것의 장점이 따로 있는지 궁금한 점이었습니다!

2023-07-05 16:48 UTC, PgmJun commented on scripts/deploy.sh
> +/home/ubuntu/app/nonstop/switch.sh
> 위에 답변을 지금 봐서 ec2 에 있는 것 확인했어요!! 혹시 scripts 폴더에 같이 올리지 않고 ec2 에 직접 올려둔 이유가 있을까욤?!

세미나에서 switch.sh 파일을 ec2내에서 보관했기에 따라서 만들다보니 그렇게 된 것 같습니다!
저도 직접 따라해보는 과정에서 ec2에서 보관하는 것의 장점을 크게 찾거나 느끼지 못하였고, 오히려 유지보수 측면에서 불편하겠다는 생각만 들었습니다..
하지만 일단 제가 이 방식을 통해 스스로 CI/CD 파이프라인을 구축해보는 것이 처음이었기 때문에 우선 작동이 되도록 구현하고 그 뒤에 곧바로 수정하려고 체크해두고 있던 부분입니다!

2023-07-05 16:51 UTC, PgmJun commented on scripts/deploy.sh
> +fi
> 이 부분을 봐주시면 좋을 것 같은데 `CURRENT_PORT` 로 dev1, dev2 를 구별하는 역할이 가능할 것 같은데 dev 를 1, 2 로 나누는 것의 장점이 따로 있는지가 궁금했습니다!

service-url.inc에서 PORT 번호를 가져와 사용하는 방법을 생각하지 못해서 생긴 문제점같습니다!ㅠㅠ
혁준님 블로그를 보고 switch.sh 파일을 수정했습니다!! 조은 레퍼런스 감사합니다!!

2023-07-06 10:08 UTC, orijoon98 reviewed
DEV 환경과 PROD 환경을 스크립트 하나로 관리하기 위해 저는 ec2 의 host name 을 지정해서 구별하는 방식으로 구현했었어요! 예를 들어 배포 서버는 lionheart-prod, 개발 서버는 lionheart-dev 이런식으로요!

https://soobarkbar.tistory.com/226

링크 참고하면 호스트 네임은 간편하게 바꿀 수 있어요!!

```
HOST_NAME=$(cat /etc/hostname)
if [ ${HOST_NAME} == "blossom-prod-server" ]; then
  nohup java -jar -Dserver.port=${TARGET_PORT} -Dspring.profiles.active=prod /home/ubuntu/blossom-api/*.jar >> /home/ubuntu/blossom-api/deploy.log 2>/home/ubuntu/blossom-api/deploy_err.log &
  echo "[$NOW_TIME] Now new WAS runs at ${TARGET_PORT}." >> /home/ubuntu/blossom-api/deploy.log
  exit 0
else
  nohup java -jar -Dserver.port=${TARGET_PORT} -Dspring.profiles.active=dev /home/ubuntu/blossom-api/*.jar >> /home/ubuntu/blossom-api/deploy.log 2>/home/ubuntu/blossom-api/deploy_err.log &
  echo "[$NOW_TIME] Now new WAS runs at ${TARGET_PORT}." >> /home/ubuntu/blossom-api/deploy.log
  exit 0
fi
``` 

이런식으로 스크립트를 작성해두고 워크플로우만 develop 에 머지하는 경우 develop ec2 로 배포하고, main 에 머지하는 경우 prod ec2 로 배포하는 식으로 구별해두면 관리가 편리했던 것 같습니당! 추가적으로 로그에 시간을 기록해두면 편해서 


```
NOW_TIME="$(date +%Y)-$(date +%m)-$(date +%d) $(date +%H):$(date +%M):$(date +%S)"
echo "[$NOW_TIME] Current port of running WAS is ${CURRENT_PORT}." >> /home/ubuntu/blossom-api/deploy.log
```

이런식으로 시간도 같이 로그에 남겨두면 찾아보기가 편했어요!!

https://github.com/Blossom-Official/blossom-server/tree/develop/scripts/blossom-api

여기서 3가지 스크립트 run_new_was.sh, health_check.sh, switch.sh 한번 참고해보시면 좋을 것 같아요!!!!

2023-07-06 11:36 UTC, PgmJun commented on scripts/deploy.sh
> +PROFILE=dev
> 지금 스크립트는 dev 환경에서만 동작이 되는 것으로 보이는데 prod 도 동일하게 사용할 수 있도록 수정이 되면 더 편할 것 같아요!!

분기처리를 하면 될까요?!

2023-07-06 11:40 UTC, PgmJun commented on .github/workflows/CI.yml
> +    branches: [ "develop" ]
> 동일한 과정이 CD 과정에 포함돼있어서 해당 워크플로우는 pull_request 때만 동작해도 될 것 같은데 어떻게 생각하시나용!!!

동의합니다!

2023-07-07 04:18 UTC, orijoon98 approved these changes
수고많으셨어용 엉엉 ㅠ_ㅠ

2023-07-07 04:18 UTC, orijoon98 commented on .github/workflows/CD-prod.yml
> +        --region ap-northeast-2
계정 두개로 dev, prod 관리하면 아마 key 값도 dev, prod 로 분리해서 관리해야하긴할텐데, 이건 나중에 prod 환경 세팅할 때 수정해도 될 것 같아요!!

2023-07-07 04:38 UTC, PgmJun commented on .github/workflows/CD-prod.yml
> +        --region ap-northeast-2
> 계정 두개로 dev, prod 관리하면 아마 key 값도 dev, prod 로 분리해서 관리해야하긴할텐데, 이건 나중에 prod 환경 세팅할 때 수정해도 될 것 같아요!!

그때하면 까먹을 수도 있으니 지금 처리 해놓겠웁니다!!!!

2023-07-07 04:45 UTC, sookyungg approved these changes

2023-07-07 08:15 UTC, merged