✨: feat 아티클 북마크 목록 조회 구현 #31
gosopt-LionHeart/LionHeart-Server pull request #32
Opened 2023-07-13 11:12 UTC by sookyungg

## ✒️ 관련 이슈번호

- Closes #31 

## 🔑 Key Changes

1. 내용
    - 아티클 북마크 목록 조회 시 태명과 북마크한 아티클을 조회 

## 📢 To Reviewers
-

2023-07-13 11:22 UTC, orijoon98 requested changes
작은 수정 몇가지 있습니다!

2023-07-13 11:22 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/articlebookmark/ArticleBookmarkRetrieveController.java
> +		return ApiResponse.success(articleBookmarkRetrieveService.getArticleBookmark(memberId));
메서드명도 복수로가능할까유?! getArticleBookmarks !

2023-07-13 11:22 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/ArticleBookmarkRetrieveService.java
> +	public ArticleBookmarkResponse getArticleBookmark(Long memberId) {
메서드명도 복수로가능할까유?! getArticleBookmarks !

2023-07-13 15:48 UTC, orijoon98 approved these changes
고생했떠염~

2023-07-14 03:02 UTC, PgmJun reviewed
수고하셨습니다!~~

2023-07-14 03:02 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/dto/response/ArticleSummaryDto.java
> +			.bookmarkStatus(articleBookmark.getMember().getId().equals(member.getId()))
findArticleBookmarksByMember 메서드로 맴버 정보를 통해서 bookmark정보를 가져오고,
그 내용을 또다시 member.getId와 비교하는 이유가 궁금합니다!

추가로 해당 메서드는 반복문에서 사용하는데 계속 반복해서 getMember()를 수행해도
findArticleBookmarksByMember 메서드로 맴버 정보를 통해서 가져온 데이터라서 같은 Member 정보일텐데
계속 getMember()를 수행하는 코드는 좋지 못한 것 같습니다..!

2023-07-14 05:51 UTC, sookyungg commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/ArticleBookmarkRetrieveService.java
> +	public ArticleBookmarkResponse getArticleBookmarks(Long memberId) {
getArticleBookmarksByMemberId로 바꿀게요옹!

2023-07-14 05:57 UTC, sookyungg commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/dto/response/ArticleSummaryDto.java
> +			.bookmarkStatus(articleBookmark.getMember().getId().equals(member.getId()))
true 로 바꿔놓을게용.........!

2023-07-14 06:13 UTC, PgmJun approved these changes

2023-07-14 06:14 UTC, merged