✨: feat 아티클 상세 조회 기능 구현 #24
gosopt-LionHeart/LionHeart-Server pull request #36
Opened 2023-07-13 15:58 UTC by PgmJun

## ✒️ 관련 이슈번호

- Closes #24 

## 🔑 Key Changes

1. 내용
    - 아티클 상세 조회 기능 구현
    - 출석체크 기능 구현

## 📢 To Reviewers
- 헤헤 놀고싶어요

2023-07-13 16:15 UTC, sookyungg requested changes
넘너무 고생하셨습니다 🤗🤗🤗🤗

2023-07-13 16:15 UTC, sookyungg commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/ArticleBookmarkServiceUtils.java
> -	public static Article findArticleById(ArticleRepository articleRepository, Long articleId) {
옮겨주셨군여.............!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! 
감사합니다

2023-07-13 16:15 UTC, sookyungg commented on lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
> +	NOT_FOUND_MEMBER_ATTENDANCE_DATA_EXCEPTION("N006", "해당 유저의 출석체크 정보가 존재하지 않습니다"),
제가 착각했나봐용 ㅜㅡㅜ 6이 아니라 7이였네요!
N006 이 이미 있어서 7로 수정 부탁 드려도 될까용????

2023-07-14 04:29 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/articlebookmark/ArticleBookmarkServiceUtils.java
> -	public static Article findArticleById(ArticleRepository articleRepository, Long articleId) {
헤헤 고럼요~~!

2023-07-14 04:29 UTC, PgmJun commented on lionheart-common/src/main/java/com/chiwawa/lionheart/common/exception/ErrorCode.java
> +	NOT_FOUND_MEMBER_ATTENDANCE_DATA_EXCEPTION("N006", "해당 유저의 출석체크 정보가 존재하지 않습니다"),
네넨!!

2023-07-14 04:41 UTC, orijoon98 requested changes

2023-07-14 05:33 UTC, merged