✨: feat 슬랙 Webhook으로 미처리 예외알림 기능 구현 #46
gosopt-LionHeart/LionHeart-Server pull request #47
Opened 2023-07-16 06:46 UTC by PgmJun

## ✒️ 관련 이슈번호

- Closes #46 

## 🔑 Key Changes

1. 내용
    
## 📢 To Reviewers
- SQS는 관련 자료가 많이 존재하지 않아서 ControllerAdvice에서Exception.class가 ExceptionHandler에 잡히면 
-

2023-07-16 10:06 UTC, orijoon98 requested changes
슬랙 서비스를 알림 서버에 두는 방식으로 한 번 진행해보면 어떨까 하구 RC 남깁니당!!

2023-07-16 10:06 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/article/ArticleRetrieveController.java
> +	}
테스트용으로 만든거같은데 지워야할것같아요~!!

2023-07-16 10:06 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
>  		return ApiResponse.error(INTERNAL_SERVER_EXCEPTION);
500, 502 모두 확인하면 더 좋을것같아요!! 그리고 지금 방식은 api 서버에서 바로 500 에러에 대해 슬랙 알림을 호출하는 방식인데, 저희가 논의한 것처럼 슬랙 서비스는 알림 서버에 두고, sqs 요청을 통해 알림 서버에서 슬랙 서비스가 호출되도록 하면 더 좋을 것 같아용! 슬랙 서비스를 알림 서버에 두고 알림서버의 스케줄러 에러 핸들러에서도 슬랙 서비스를 호출하면 api 서버, 알림 서버 모두 슬랙으로 에러 모니터링 가능할것같아요!

2023-07-16 10:10 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +		}
주석 "프로필" 로 수정 가능할까욤?!

2023-07-16 10:10 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +						"https://user-images.githubusercontent.com/64000241/252282249-08381e4c-15b5-42b9-8ffc-1e887e688f16.png")
이거 이미지는 어디에 저장돼있는건지 궁금해욤!

2023-07-16 19:34 UTC, sookyungg approved these changes
주석 써주셔서 이해하기 너무 편했어요 :)))))

2023-07-17 10:23 UTC, orijoon98 requested changes
전체적인 로직은 잘 완성된것같아욤!!!! 몇가지 수정사항만 반영해주시면 감사하겠습니당 :)

2023-07-17 10:23 UTC, orijoon98 commented on lionheart-api/build.gradle
> +
슬랙 서비스 알림 서버로 옮겨서 여기선 이제 지워도 되지 않을까요?!

2023-07-17 10:23 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
>  		return ApiResponse.error(INTERNAL_SERVER_EXCEPTION);
502도 서버쪽에서 처리해야할 에러일 수 있어서 위에 Bad Gateway 에러에도 슬랙 알림 추가하면 좋을 것 같아요!

2023-07-17 10:23 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/article/ArticleRetrieveController.java
> +	}
이거 리마인드요~

2023-07-17 10:23 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/NotificationService.java
지금 당장은 readOnly=true 해도 문제 없긴한데, 저희 retrieveService 에 붙이는 컨벤션이 있기도 하구, 해당 서비스는 조회 느낌보다는 메시지를 발행하는 서비스라 기존대로 가는게 어떨까요?!

2023-07-17 10:23 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/NotificationService.java
그리구 getRequestUri 도 카멜케이스로 가는거 어떨까요!!

2023-07-17 11:45 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +		}
물론이죠잉~~

2023-07-17 11:51 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/advice/ControllerAdvice.java
>  		return ApiResponse.error(INTERNAL_SERVER_EXCEPTION);
HttpServletRequest 클래스가 spring-web 의존성을 가지고있지 않은 notification 모듈에선 import가 불가능해서,
우선 이렇게 구현했는데요! HttpServletRequest에서 httpMethod와 httpRequestUrl을 추출하여 DTO객체로 만들어 해결하였습니다~~! 감사합니다~!

2023-07-17 11:55 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +		}
참고로 프로파일로 기록한 이유는!
프로필은 profil이라는 프랑스어의 발음이고
profile은 영어로 프로파일이라고 발음한다고 하더군요!
뜻은 같지만 영단어인 profile을 사용하기 때문에 프로파일로 표기하고 있었습니다!

2023-07-17 11:57 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +						"https://user-images.githubusercontent.com/64000241/252282249-08381e4c-15b5-42b9-8ffc-1e887e688f16.png")
깃허브에 저장되어 있는 이미지 입니다!

2023-07-17 13:30 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/notification/slack/SlackService.java
> +		}
오홍 처음 알았어요!!! 알겠습니당!!

2023-07-17 16:43 UTC, orijoon98 approved these changes
좋앗쒀~ 용촤~

2023-07-17 16:44 UTC, merged