Feat/#6 카카오 로그인 기능 추가
gosopt-LionHeart/LionHeart-Server pull request #7
Opened 2023-07-07 07:48 UTC by sookyungg

## ✒️ 관련 이슈번호

- Closes #6 

## 🔑 Key Changes

1. 내용
    - 카카오 로그인 기능 추가하였습니다..!

## 📢 To Reviewers
-

2023-07-07 08:17 UTC, orijoon98 requested changes
자잘한 수정이 많습니당!! user -> member !!
우리 로그에 남기는 유저 -> 회원
이렇게 수정이 대부분인 것 같아요!! 고생하셨습니당 :)

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/AuthInterceptor.java
> +		return true;
변수명 이랑 메서드명 memberId 로 부탁해요!!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
> +		String bearerToken = request.getHeader("Authorization");
getMemberId !!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
> +					return userId;
memberId!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/resolver/MemberIdResolver.java
> +		}
MEMBER_ID 로 부탁드려요!!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/auth/AuthController.java
> +		TokenResponse tokenInfo = createTokenService.createTokenInfo(userId);
여기두 memberId~!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/auth/AuthController.java
> +		TokenResponse tokenInfo = createTokenService.createTokenInfo(userId);
memberId!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/controller/auth/AuthController.java
> +		return ApiResponse.SUCCESS;
memberId!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CommonAuthService.java
> +
memberRepository!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CommonAuthService.java
> +	}
user 전부 member 로 부탁합니당 ㅋㅋ

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/CreateTokenService.java
> +	}
여기두 memberRepository memberId 부탁합니다!!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/request/LoginRequest.java
> +	private String token;
여기에 message = "{auth.socialType.notNull}" 이 부분은 따로 validation 관련 파일을 만들어줘야 반영이 돼요!!
이 부분 따로 질문 주세용!!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/response/TokenResponse.java
> +	private String refreshToken;
라이옹 의도한건가요..?! ㅋㅋㅋ

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberService.java
> +	private String profile;
이거 필요없을 것 같은데 지울까요?!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberServiceUtils.java
> +	}
memberId

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberServiceUtils.java
> +	}
메시지에 들어가는 유저도 저희 '회원'으로 통일하면 좋을 것 같아요!

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-common/src/main/java/com.chiwawa.lionheart.common/constant/Constraint.java
> +}
네이밍 MEMBER_NICKNAME_MAX !

2023-07-07 08:17 UTC, orijoon98 commented on lionheart-common/src/main/java/com.chiwawa.lionheart.common/util/JwtUtils.java
> +	}
여기도 memberId!

2023-07-07 10:27 UTC, sookyungg commented on lionheart-common/src/main/java/com.chiwawa.lionheart.common/util/JwtUtils.java
> +	}
아구구 바꿔놓는다고 바꿔 놓았는데 빠뜨린 것들이 많네요! 수정 하겠습니다!

2023-07-07 11:42 UTC, sookyungg commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/response/TokenResponse.java
> +	private String refreshToken;
ㅎㅎ..ㅎㅎㅎ..ㅎㅎㅎ..ㅎ

2023-07-08 16:19 UTC, PgmJun reviewed
완전완전 열심히 하셨군요!!! 수고하셨습니다!!
궁금한 점 남겼는데 확인부탁드려요!!!

2023-07-08 16:19 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/auth/dto/response/TokenResponse.java
> +	private String refreshToken;
걸어봐 위엄 like a 라이옹~~

2023-07-08 16:19 UTC, PgmJun commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/service/member/MemberServiceUtils.java
> +public class MemberServiceUtils {
@orijoon98 @sookyungg 
Service객체를 Util클래스로 관리하는 방식은 처음봤는데 신기하네요!!
혹시 이렇게 Util 형태로 관리하는 이유가 뭔지 알 수 있을까요!?
궁금합니다!!

2023-07-10 10:34 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
> +				if (userId != null) {
동의합니다.

2023-07-10 10:34 UTC, orijoon98 commented on lionheart-api/src/main/java/com/chiwawa/lionheart/api/config/interceptor/auth/LoginCheckHandler.java
> +		throw new UnAuthorizedException(String.format("잘못된 JWT (%s) 입니다.", bearerToken));
진행해주세요.

2023-07-11 13:43 UTC, merged